Improve performance
lehins/random pull request #103
Opened 2020-04-21 18:39 UTC by lehins

This PR fixes:

* Performance issue that I discovered when benchmarking generation of integral values in a range
* Order of arguments in `uniformR` function was inconsistent with other range functions.

2020-04-21 19:54 UTC, curiousleo commented
>     * Performance issue that I discovered when benchmarking generation of integral values in a range

Nice! How big is the performance boost?

2020-04-21 19:55 UTC, curiousleo approved these changes

2020-04-21 20:03 UTC, lehins commented
@curiousleo Pretty significant ~x20. Problem is when a function is recursive, then it cannot be inlined, which can hurt the performance really bad when that function is being called many many times.
In case of `[un]signedBitmaskWithRejectionRM` there was no need for them to be recursive.

Haven't tried the internal benchmarks, but running with criterion difference in performance was obvious.

2020-04-21 21:44 UTC, lehins commented
@curiousleo Applied the same fix of removing recursion to Integer generation, got quite a bit of performance boost as well ;)

Benchmarks for ranges are available in the same place: https://github.com/lehins/haskell-benchmarks/tree/new-random/new-random-benchmarks

2020-04-22 11:05 UTC, curiousleo approved these changes

2020-04-23 11:35 UTC, curiousleo commented
Fixed a semantic merge conflict: https://github.com/idontgetoutmuch/random/pull/103/commits/068aa36280a44a61e358f8d12697d43497e8f2a8#diff-5b60458897b8b814de6d596bdc71e75cL210-R210

2020-04-23 13:45 UTC, curiousleo commented
According to the new benchmarks, this is a massive improvement for some types (e.g. `Word64`) and a slight performance regression for others (e.g. `Word16`).

```
                                         mean BEFORE    AFTER     error BEFORE     AFTER
pure/uniformR/full/Word16                mean 28.35 μs  17.96 ms  ( +- 1.383 μs  ) ( +- 1.369 ms  )
pure/uniformR/full/Word64                mean 1.552 ms  131.3 μs  ( +- 103.9 μs  ) ( +- 3.496 μs  )
```

Full comparison in [compare.txt](https://github.com/idontgetoutmuch/random/files/4522819/compare.txt).

[improve-performance-bb7b99a.txt](https://github.com/idontgetoutmuch/random/files/4522820/improve-performance-bb7b99a.txt)
[interface-to-performance-d03e325.txt](https://github.com/idontgetoutmuch/random/files/4522821/interface-to-performance-d03e325.txt)

2020-04-23 13:49 UTC, curiousleo requested changes
Amongst performance improvements, this also contains performance regressions: https://github.com/idontgetoutmuch/random/pull/103#issuecomment-618402784

2020-05-05 13:35 UTC, curiousleo commented
Ping @lehins - I've cherry-picked most performance improvements from here onto #116, which is now merged. I've played around with the optimisation you made to `uniformIntegerM` (making it non-recursive). This has strange side-effects: in my benchmarks, it makes other generators run slower. I won't pursue this particular optimisation further for now.

2020-05-08 14:27 UTC, lehins commented
I am closing this, since most of improvements were cherry picked

2020-05-08 14:27 UTC, closed without merging